package com.snow.freedomarmy.admin.app.dao.mapper.website_preview;

import com.snow.freedomarmy.admin.app.core.model.website_preview.Works;
import com.snow.freedomarmy.admin.app.core.model.website_preview.WorksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_preview..works
     *
     * @mbggenerated
     */
    int countByExample(WorksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_preview..works
     *
     * @mbggenerated
     */
    int deleteByExample(WorksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_preview..works
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_preview..works
     *
     * @mbggenerated
     */
    int insert(Works record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_preview..works
     *
     * @mbggenerated
     */
    int insertSelective(Works record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_preview..works
     *
     * @mbggenerated
     */
    List<Works> selectByExample(WorksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_preview..works
     *
     * @mbggenerated
     */
    Works selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_preview..works
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Works record, @Param("example") WorksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_preview..works
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Works record, @Param("example") WorksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_preview..works
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Works record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_preview..works
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Works record);
}