package com.snow.freedomarmy.admin.app.dao.mapper;

import com.snow.freedomarmy.admin.app.core.model.CommodityType;
import com.snow.freedomarmy.admin.app.core.model.CommodityTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommodityTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbggenerated
     */
    int countByExample(CommodityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbggenerated
     */
    int deleteByExample(CommodityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbggenerated
     */
    int insert(CommodityType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbggenerated
     */
    int insertSelective(CommodityType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbggenerated
     */
    List<CommodityType> selectByExample(CommodityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbggenerated
     */
    CommodityType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CommodityType record, @Param("example") CommodityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CommodityType record, @Param("example") CommodityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommodityType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommodityType record);
}