package com.snow.freedomarmy.admin.app.dao.mapper;

import com.snow.freedomarmy.admin.app.core.model.CommodityImage;
import com.snow.freedomarmy.admin.app.core.model.CommodityImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommodityImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_image
     *
     * @mbggenerated
     */
    int countByExample(CommodityImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_image
     *
     * @mbggenerated
     */
    int deleteByExample(CommodityImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_image
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_image
     *
     * @mbggenerated
     */
    int insert(CommodityImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_image
     *
     * @mbggenerated
     */
    int insertSelective(CommodityImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_image
     *
     * @mbggenerated
     */
    List<CommodityImage> selectByExample(CommodityImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_image
     *
     * @mbggenerated
     */
    CommodityImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_image
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CommodityImage record, @Param("example") CommodityImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_image
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CommodityImage record, @Param("example") CommodityImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommodityImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommodityImage record);
}