package com.snow.freedomarmy.admin.app.core.model;

public class Commodity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodity_name
     *
     * @mbggenerated
     */
    private String commodityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodity_price
     *
     * @mbggenerated
     */
    private String commodityPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.browsing_volume
     *
     * @mbggenerated
     */
    private Integer browsingVolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.parent
     *
     * @mbggenerated
     */
    private Integer parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.grandpa
     *
     * @mbggenerated
     */
    private Integer grandpa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.stock
     *
     * @mbggenerated
     */
    private Integer stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.integral
     *
     * @mbggenerated
     */
    private Integer integral;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.id
     *
     * @return the value of commodity.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.id
     *
     * @param id the value for commodity.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodity_name
     *
     * @return the value of commodity.commodity_name
     *
     * @mbggenerated
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodity_name
     *
     * @param commodityName the value for commodity.commodity_name
     *
     * @mbggenerated
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName == null ? null : commodityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodity_price
     *
     * @return the value of commodity.commodity_price
     *
     * @mbggenerated
     */
    public String getCommodityPrice() {
        return commodityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodity_price
     *
     * @param commodityPrice the value for commodity.commodity_price
     *
     * @mbggenerated
     */
    public void setCommodityPrice(String commodityPrice) {
        this.commodityPrice = commodityPrice == null ? null : commodityPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.browsing_volume
     *
     * @return the value of commodity.browsing_volume
     *
     * @mbggenerated
     */
    public Integer getBrowsingVolume() {
        return browsingVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.browsing_volume
     *
     * @param browsingVolume the value for commodity.browsing_volume
     *
     * @mbggenerated
     */
    public void setBrowsingVolume(Integer browsingVolume) {
        this.browsingVolume = browsingVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.parent
     *
     * @return the value of commodity.parent
     *
     * @mbggenerated
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.parent
     *
     * @param parent the value for commodity.parent
     *
     * @mbggenerated
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.grandpa
     *
     * @return the value of commodity.grandpa
     *
     * @mbggenerated
     */
    public Integer getGrandpa() {
        return grandpa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.grandpa
     *
     * @param grandpa the value for commodity.grandpa
     *
     * @mbggenerated
     */
    public void setGrandpa(Integer grandpa) {
        this.grandpa = grandpa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.stock
     *
     * @return the value of commodity.stock
     *
     * @mbggenerated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.stock
     *
     * @param stock the value for commodity.stock
     *
     * @mbggenerated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.integral
     *
     * @return the value of commodity.integral
     *
     * @mbggenerated
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.integral
     *
     * @param integral the value for commodity.integral
     *
     * @mbggenerated
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }
}