package com.snow.freedomarmy.admin.app.core.model;

public class CommodityImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_image.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_image.image_name
     *
     * @mbggenerated
     */
    private String imageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_image.commodity_parent
     *
     * @mbggenerated
     */
    private Integer commodityParent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_image.id
     *
     * @return the value of commodity_image.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_image.id
     *
     * @param id the value for commodity_image.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_image.image_name
     *
     * @return the value of commodity_image.image_name
     *
     * @mbggenerated
     */
    public String getImageName() {
        return imageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_image.image_name
     *
     * @param imageName the value for commodity_image.image_name
     *
     * @mbggenerated
     */
    public void setImageName(String imageName) {
        this.imageName = imageName == null ? null : imageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_image.commodity_parent
     *
     * @return the value of commodity_image.commodity_parent
     *
     * @mbggenerated
     */
    public Integer getCommodityParent() {
        return commodityParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_image.commodity_parent
     *
     * @param commodityParent the value for commodity_image.commodity_parent
     *
     * @mbggenerated
     */
    public void setCommodityParent(Integer commodityParent) {
        this.commodityParent = commodityParent;
    }
}