package com.snow.freedomarmy.admin.app.core.model;

public class CommodityComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_comment.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_comment.commenttext
     *
     * @mbggenerated
     */
    private String commenttext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_comment.commentimage
     *
     * @mbggenerated
     */
    private String commentimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_comment.commodityparent
     *
     * @mbggenerated
     */
    private Integer commodityparent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_comment.userparent
     *
     * @mbggenerated
     */
    private Integer userparent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_comment.id
     *
     * @return the value of commodity_comment.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_comment.id
     *
     * @param id the value for commodity_comment.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_comment.commenttext
     *
     * @return the value of commodity_comment.commenttext
     *
     * @mbggenerated
     */
    public String getCommenttext() {
        return commenttext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_comment.commenttext
     *
     * @param commenttext the value for commodity_comment.commenttext
     *
     * @mbggenerated
     */
    public void setCommenttext(String commenttext) {
        this.commenttext = commenttext == null ? null : commenttext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_comment.commentimage
     *
     * @return the value of commodity_comment.commentimage
     *
     * @mbggenerated
     */
    public String getCommentimage() {
        return commentimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_comment.commentimage
     *
     * @param commentimage the value for commodity_comment.commentimage
     *
     * @mbggenerated
     */
    public void setCommentimage(String commentimage) {
        this.commentimage = commentimage == null ? null : commentimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_comment.commodityparent
     *
     * @return the value of commodity_comment.commodityparent
     *
     * @mbggenerated
     */
    public Integer getCommodityparent() {
        return commodityparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_comment.commodityparent
     *
     * @param commodityparent the value for commodity_comment.commodityparent
     *
     * @mbggenerated
     */
    public void setCommodityparent(Integer commodityparent) {
        this.commodityparent = commodityparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_comment.userparent
     *
     * @return the value of commodity_comment.userparent
     *
     * @mbggenerated
     */
    public Integer getUserparent() {
        return userparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_comment.userparent
     *
     * @param userparent the value for commodity_comment.userparent
     *
     * @mbggenerated
     */
    public void setUserparent(Integer userparent) {
        this.userparent = userparent;
    }
}