package com.snow.freedomarmy.admin.app.core.model;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.commodity_id
     *
     * @mbggenerated
     */
    private Integer commodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.commodity_number
     *
     * @mbggenerated
     */
    private Integer commodityNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_price
     *
     * @mbggenerated
     */
    private String ordersPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.is_payment
     *
     * @mbggenerated
     */
    private Integer isPayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.is_send_goods
     *
     * @mbggenerated
     */
    private Integer isSendGoods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.is_collect_goods
     *
     * @mbggenerated
     */
    private Integer isCollectGoods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.is_collect_money
     *
     * @mbggenerated
     */
    private Integer isCollectMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.is_return_goods
     *
     * @mbggenerated
     */
    private Integer isReturnGoods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.is_exchange_goods
     *
     * @mbggenerated
     */
    private Integer isExchangeGoods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.is_refund
     *
     * @mbggenerated
     */
    private Integer isRefund;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.username
     *
     * @return the value of orders.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.username
     *
     * @param username the value for orders.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.commodity_id
     *
     * @return the value of orders.commodity_id
     *
     * @mbggenerated
     */
    public Integer getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.commodity_id
     *
     * @param commodityId the value for orders.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.commodity_number
     *
     * @return the value of orders.commodity_number
     *
     * @mbggenerated
     */
    public Integer getCommodityNumber() {
        return commodityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.commodity_number
     *
     * @param commodityNumber the value for orders.commodity_number
     *
     * @mbggenerated
     */
    public void setCommodityNumber(Integer commodityNumber) {
        this.commodityNumber = commodityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_price
     *
     * @return the value of orders.orders_price
     *
     * @mbggenerated
     */
    public String getOrdersPrice() {
        return ordersPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_price
     *
     * @param ordersPrice the value for orders.orders_price
     *
     * @mbggenerated
     */
    public void setOrdersPrice(String ordersPrice) {
        this.ordersPrice = ordersPrice == null ? null : ordersPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.is_payment
     *
     * @return the value of orders.is_payment
     *
     * @mbggenerated
     */
    public Integer getIsPayment() {
        return isPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.is_payment
     *
     * @param isPayment the value for orders.is_payment
     *
     * @mbggenerated
     */
    public void setIsPayment(Integer isPayment) {
        this.isPayment = isPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.is_send_goods
     *
     * @return the value of orders.is_send_goods
     *
     * @mbggenerated
     */
    public Integer getIsSendGoods() {
        return isSendGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.is_send_goods
     *
     * @param isSendGoods the value for orders.is_send_goods
     *
     * @mbggenerated
     */
    public void setIsSendGoods(Integer isSendGoods) {
        this.isSendGoods = isSendGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.is_collect_goods
     *
     * @return the value of orders.is_collect_goods
     *
     * @mbggenerated
     */
    public Integer getIsCollectGoods() {
        return isCollectGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.is_collect_goods
     *
     * @param isCollectGoods the value for orders.is_collect_goods
     *
     * @mbggenerated
     */
    public void setIsCollectGoods(Integer isCollectGoods) {
        this.isCollectGoods = isCollectGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.is_collect_money
     *
     * @return the value of orders.is_collect_money
     *
     * @mbggenerated
     */
    public Integer getIsCollectMoney() {
        return isCollectMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.is_collect_money
     *
     * @param isCollectMoney the value for orders.is_collect_money
     *
     * @mbggenerated
     */
    public void setIsCollectMoney(Integer isCollectMoney) {
        this.isCollectMoney = isCollectMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.is_return_goods
     *
     * @return the value of orders.is_return_goods
     *
     * @mbggenerated
     */
    public Integer getIsReturnGoods() {
        return isReturnGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.is_return_goods
     *
     * @param isReturnGoods the value for orders.is_return_goods
     *
     * @mbggenerated
     */
    public void setIsReturnGoods(Integer isReturnGoods) {
        this.isReturnGoods = isReturnGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.is_exchange_goods
     *
     * @return the value of orders.is_exchange_goods
     *
     * @mbggenerated
     */
    public Integer getIsExchangeGoods() {
        return isExchangeGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.is_exchange_goods
     *
     * @param isExchangeGoods the value for orders.is_exchange_goods
     *
     * @mbggenerated
     */
    public void setIsExchangeGoods(Integer isExchangeGoods) {
        this.isExchangeGoods = isExchangeGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.is_refund
     *
     * @return the value of orders.is_refund
     *
     * @mbggenerated
     */
    public Integer getIsRefund() {
        return isRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.is_refund
     *
     * @param isRefund the value for orders.is_refund
     *
     * @mbggenerated
     */
    public void setIsRefund(Integer isRefund) {
        this.isRefund = isRefund;
    }
}