package com.snow.freedomarmy.admin.app.core.model.website_preview;

public class Works {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_preview..works.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_preview..works.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_preview..works.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_preview..works.Introduce
     *
     * @mbggenerated
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_preview..works.technology
     *
     * @mbggenerated
     */
    private String technology;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_preview..works.member
     *
     * @mbggenerated
     */
    private String member;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_preview..works.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_preview..works.id
     *
     * @return the value of website_preview..works.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_preview..works.id
     *
     * @param id the value for website_preview..works.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_preview..works.user_id
     *
     * @return the value of website_preview..works.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_preview..works.user_id
     *
     * @param userId the value for website_preview..works.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_preview..works.name
     *
     * @return the value of website_preview..works.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_preview..works.name
     *
     * @param name the value for website_preview..works.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_preview..works.Introduce
     *
     * @return the value of website_preview..works.Introduce
     *
     * @mbggenerated
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_preview..works.Introduce
     *
     * @param introduce the value for website_preview..works.Introduce
     *
     * @mbggenerated
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_preview..works.technology
     *
     * @return the value of website_preview..works.technology
     *
     * @mbggenerated
     */
    public String getTechnology() {
        return technology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_preview..works.technology
     *
     * @param technology the value for website_preview..works.technology
     *
     * @mbggenerated
     */
    public void setTechnology(String technology) {
        this.technology = technology == null ? null : technology.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_preview..works.member
     *
     * @return the value of website_preview..works.member
     *
     * @mbggenerated
     */
    public String getMember() {
        return member;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_preview..works.member
     *
     * @param member the value for website_preview..works.member
     *
     * @mbggenerated
     */
    public void setMember(String member) {
        this.member = member == null ? null : member.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_preview..works.url
     *
     * @return the value of website_preview..works.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_preview..works.url
     *
     * @param url the value for website_preview..works.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}